version: '3.9'
services:
  case-vault-back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  case-vault-front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/package.json:/app/package.json
    ports:
      - "3001:3001"